---
title: "Alphaviruses in Panama"
subtitle: "FOI models fitted to age-structured sero-prevalence"
output:
  html_document:
    df_print: paged
---

```{r, warning=FALSE, echo=FALSE, message=FALSE}
rm(list=ls())
library(rstan)
library(tidyverse)
library(reshape2)
library(bayesplot)
library(loo)
library(pracma)
library(cowplot)
library(grid)
library(gridExtra)
source('fun/additional_functions.R')
source('fun/FitAndPlot_function_final.R')
options(mc.cores = 4)

```


```{r, echo = FALSE}
# model1 <- stan_model("models/constant_foi.stan")
# model2 <- stan_model("models/decades_foi_uniform.stan")
# model3 <- stan_model("models/decades_foi_student_t.stan")
# 
# saveRDS(model1, 'models/model1.RDS')
# saveRDS(model2, 'models/model2.RDS')
# saveRDS(model3, 'models/model3.RDS')

# ---- Models
model1 <-readRDS('models/model1.RDS')
model2 <-readRDS('models/model3.RDS')

```




```{r, echo = TRUE}
# ---- Datasets
dat1 <- readRDS('data/Panama2012.RDS') %>% mutate(PlaceName = 'Darien',  id = stringr::str_sub(dataset_id, 1, 3))
dat2 <- readRDS('data/Panama2017.RDS') %>% mutate(PlaceName = 'Mogue',  id = stringr::str_sub(dataset_id, 1, 3))
dat3 <- readRDS('data/Panama2012_places.RDS')%>% mutate(survey = dataset_id)


dat0   <- rbind(dat3, dat1, dat2) %>% filter(id %in% c('005'))
dat0$virus[dat0$virus=='UNA'] <- 'UNAV' 
dat0 <- dat0 %>%  mutate(counts = pos,
                         survey = paste(virus,tsur, PlaceName, id)) %>%
  arrange(desc(survey)) %>%  mutate(age_mean_f = floor((age_min + age_max)/2))
rm(dat1, dat2, dat3)

(datasets <- unique(dat0$survey))


```

```{r, fig.width = 10, fig.height = 10, message=FALSE, warning=FALSE, results = "hide", out.width = "100%"}

for (s in datasets)
{
  
  dat <- filter(dat0, survey == s) %>% arrange(age_mean_f) %>%
    mutate(birth_year = tsur - age_mean_f)
  
  res1  <- fFitModel(model1, dat)
  res2  <- fFitModel(model2, dat)
  
  
  plot_res1 <- fPlotModel(res1, dat, 'constant', 'uniform')
  plot_res2 <- fPlotModelDecades(res2, dat, 'decades', 'student_t')
  
  
  grid.arrange(plot_res1, plot_res2, nrow =1)

  res_survey <- list(dat  = dat,
                     mod1  = res1,
                     mod2  = res2)


  saveRDS(res_survey, paste0('res_final_10000/', s, '.RDS' ))


  rm(dat, res1, res2, plot_res1, plot_res2, res_survey)

  }







```




